### ISSUE TITLE
增量备份功能？

### ISSUE THREAD

**Issue by sydney0zq** [LitoMore/nofan#29]
初步设想，拉取当前用户的timeline，然后以`FanfouSDK`中的消息字段存储到SQLite数据库中。之后从数据库中拉取所有的图片links，单线程下载且加入延迟，避免饭否服务器压力过大。之后在视觉层可以用其他语言写为Markdown/HTML格式，这方面pyfanfou已经做的差不多了，可以直接复用。

增量备份为找到数据库中最近日期的一天，然后不断遍历当前用户的消息，一直到最近日期的一天停止。

作者有这方面的考虑吗？

**Comment by LitoMore** [comment]
I don't think so, sorry.
