### ISSUE TITLE
How to use `reply` and `repost` command

### ISSUE THREAD

**Issue by browncrane** [LitoMore/nofan#66]
Hi! @LitoMore. nofan is really good work. Thanks for the job you have done.

Currently, nofan need an id to reply status
`nofan reply|re <id> [text]   # Reply status`
However, I didn't find any way to show the most recent status id.

If there is an easy way to reply to the recent status on the timeline, it would be more fun to use nofan.

Best regards.

**Comment by LitoMore** [comment]
> However, I didn't find any way to show the most recent status id.

@browncrane You could use the `--verbose` flag for output more imformation.

![image](https://user-images.githubusercontent.com/8186898/53691001-718b3e00-3db0-11e9-889f-5f1efe65d464.png)

**Comment by browncrane** [comment]
Cool! Would you mind to put this information in the `README.md`
The `--verbose` is already in `-h` usage information.
It would be perfect if the description could be more explicit.

**Comment by LitoMore** [comment]
> Cool! Would you mind to put this information in the README.md

Sure.
