### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sydney0zq** [LitoMore/nofan#73]
Thanks for developing such a wonderful project.

If some plain user wants to install `nofan` on a server without administration. Is there any way to do that? I have tried it, but some error happens:

```
npm ERR! Linux 3.10.0-862.14.4.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "nofan"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data-1/$USERNAME$/RUN/npm-debug.log
```

When I try using `npm -i nofan`, a different error happens:

```
npm WARN enoent ENOENT: no such file or directory, open '/mnt/data-1/$USERNAME$/RUN/package.json'
npm WARN RUN No description
npm WARN RUN No repository field.
npm WARN RUN No README data
npm WARN RUN No license field.
```

Thanks.

**Comment by LitoMore** [comment]
You could use `sudo npm i -g nofan` to install this package, or resolve your file permissions by following this [documentation](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) from npm official.

**Comment by LitoMore** [comment]
```
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
```

By the way, Nofan is required Node.js 8 or later. Please upgrade your Node.js.

**Comment by LitoMore** [comment]
@sydney0zq It's a common issue of npm. So I'm going to close this issue. Thank you for your feedback!
